
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Nov 17 23:32:00 EST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 12;
  public static final int rw_WHILE = 15;
  public static final int rw_BOOL = 16;
  public static final int LBRACKET = 30;
  public static final int rw_IF = 11;
  public static final int SLASH = 31;
  public static final int rw_CONTINUE = 17;
  public static final int rw_FALSE = 18;
  public static final int LPAREN = 4;
  public static final int SEMI = 3;
  public static final int rw_PRINT = 19;
  public static final int rw_TRUE = 20;
  public static final int MINUS = 10;
  public static final int RPAREN = 5;
  public static final int NOT = 32;
  public static final int INTLIT = 14;
  public static final int rw_VOID = 21;
  public static final int LT = 33;
  public static final int rw_CONST = 22;
  public static final int COMMA = 34;
  public static final int INC = 35;
  public static final int GEQ = 36;
  public static final int rw_ELSE = 23;
  public static final int PLUS = 9;
  public static final int rw_READ = 24;
  public static final int rw_INT = 25;
  public static final int EOF = 0;
  public static final int rw_FOR = 48;
  public static final int RBRACKET = 37;
  public static final int error = 1;
  public static final int COR = 38;
  public static final int rw_CLASS = 26;
  public static final int EQ = 39;
  public static final int rw_RETURN = 27;
  public static final int ASG = 6;
  public static final int TIMES = 40;
  public static final int CHARLIT = 13;
  public static final int COLON = 41;
  public static final int LBRACE = 7;
  public static final int rw_CHAR = 28;
  public static final int CAND = 42;
  public static final int RBRACE = 8;
  public static final int LEQ = 43;
  public static final int rw_BREAK = 29;
  public static final int DEC = 44;
  public static final int rw_ENDIF = 47;
  public static final int GT = 45;
  public static final int NOTEQ = 46;
  public static final int IDENTIFIER = 2;
}

